M48
; DRILL file KiCad 10.0.1 date 2026-04-27T13:53:20
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-27T13:53:20+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X147.0Y-86.5
X157.16Y-86.5
T2
X147.0Y-98.0
X149.54Y-98.0
M30
